/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Livros;
import dao.DAOEstante;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author natim
 */
public class TelaMinhaEstante extends javax.swing.JFrame {

    /**
     * Creates new form TelaMinhaEstante
     */
    public TelaMinhaEstante(String usuario) {
        super("Minha Estante");
        initComponents();
        jLabelUsuario.setText(usuario);
        setLocationRelativeTo(null);

        DefaultTableModel modelo = (DefaultTableModel) estanteTable.getModel();

        estanteTable.getColumnModel().getColumn(0);
        estanteTable.getColumnModel().getColumn(1);
        estanteTable.getColumnModel().getColumn(2);
        estanteTable.getColumnModel().getColumn(3);
        estanteTable.getColumnModel().getColumn(4);
        estanteTable.getColumnModel().getColumn(5);
        estanteTable.getColumnModel().getColumn(6);
        estanteTable.getColumnModel().getColumn(7);

        DAOEstante daoE = new DAOEstante();

        try {

            for (Livros m : daoE.listarEstante()) {
                if (m.getUsuarioLogado().equals(jLabelUsuario.getText())) {
                    modelo.addRow(new Object[]{
                        m.getId_Livros(),
                        m.getNome(),
                        m.getAutor(),
                        m.getGenero(),
                        m.getPaginas(),
                        m.getPaginasLidas(),
                        m.getNota(),
                        m.getUsuarioLogado()
                    });
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar as músicas!");
        }
    }

    public TelaMinhaEstante() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        notaButton = new javax.swing.JButton();
        progressoButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estanteTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        zeroRadioButton = new javax.swing.JRadioButton();
        humRadioButton = new javax.swing.JRadioButton();
        doisRadioButton = new javax.swing.JRadioButton();
        tresRadioButton = new javax.swing.JRadioButton();
        quatroRadioButton = new javax.swing.JRadioButton();
        cincoRadioButton = new javax.swing.JRadioButton();
        progressoSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        detalharButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        autorjLabel = new javax.swing.JLabel();
        generojLabel = new javax.swing.JLabel();
        paginasjLabel = new javax.swing.JLabel();
        paginasLidasjLabel = new javax.swing.JLabel();
        notajLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        progressojLabel = new javax.swing.JLabel();
        voltarButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        notaButton.setBackground(new java.awt.Color(255, 204, 204));
        notaButton.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        notaButton.setForeground(new java.awt.Color(153, 0, 0));
        notaButton.setText("Atribuir Nota");
        notaButton.setFocusPainted(false);
        notaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notaButtonMouseExited(evt);
            }
        });
        notaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaButtonActionPerformed(evt);
            }
        });

        progressoButton.setBackground(new java.awt.Color(255, 204, 204));
        progressoButton.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        progressoButton.setForeground(new java.awt.Color(153, 0, 0));
        progressoButton.setText("Alterar Progresso");
        progressoButton.setFocusPainted(false);
        progressoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                progressoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                progressoButtonMouseExited(evt);
            }
        });
        progressoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressoButtonActionPerformed(evt);
            }
        });

        removerButton.setBackground(new java.awt.Color(255, 204, 204));
        removerButton.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        removerButton.setForeground(new java.awt.Color(153, 0, 0));
        removerButton.setText("Remover");
        removerButton.setFocusPainted(false);
        removerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removerButtonMouseExited(evt);
            }
        });
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        sairButton.setBackground(new java.awt.Color(255, 91, 91));
        sairButton.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        sairButton.setForeground(new java.awt.Color(153, 0, 0));
        sairButton.setText("Sair");
        sairButton.setFocusPainted(false);
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairButtonMouseExited(evt);
            }
        });
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\BookShelf.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabel3.setText("Usuario: ");

        jLabelUsuario.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("-");

        estanteTable.setBackground(new java.awt.Color(255, 255, 255));
        estanteTable.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        estanteTable.setForeground(new java.awt.Color(102, 102, 102));
        estanteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Autor", "Gênero", "Páginas", "Páginas Lidas", "Nota", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        estanteTable.setSelectionBackground(new java.awt.Color(255, 204, 204));
        estanteTable.setSelectionForeground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(estanteTable);
        if (estanteTable.getColumnModel().getColumnCount() > 0) {
            estanteTable.getColumnModel().getColumn(0).setResizable(false);
            estanteTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            estanteTable.getColumnModel().getColumn(1).setResizable(false);
            estanteTable.getColumnModel().getColumn(1).setPreferredWidth(210);
            estanteTable.getColumnModel().getColumn(2).setMinWidth(0);
            estanteTable.getColumnModel().getColumn(2).setPreferredWidth(0);
            estanteTable.getColumnModel().getColumn(2).setMaxWidth(0);
            estanteTable.getColumnModel().getColumn(3).setResizable(false);
            estanteTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            estanteTable.getColumnModel().getColumn(4).setResizable(false);
            estanteTable.getColumnModel().getColumn(4).setPreferredWidth(70);
            estanteTable.getColumnModel().getColumn(5).setMinWidth(0);
            estanteTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            estanteTable.getColumnModel().getColumn(5).setMaxWidth(0);
            estanteTable.getColumnModel().getColumn(6).setMinWidth(0);
            estanteTable.getColumnModel().getColumn(6).setPreferredWidth(0);
            estanteTable.getColumnModel().getColumn(6).setMaxWidth(0);
            estanteTable.getColumnModel().getColumn(7).setMinWidth(0);
            estanteTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            estanteTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        jLabel4.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel4.setText("Minha Estante");

        zeroRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(zeroRadioButton);
        zeroRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        zeroRadioButton.setText("0");
        zeroRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroRadioButtonActionPerformed(evt);
            }
        });

        humRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(humRadioButton);
        humRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        humRadioButton.setText("1");
        humRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humRadioButtonActionPerformed(evt);
            }
        });

        doisRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(doisRadioButton);
        doisRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        doisRadioButton.setText("2");
        doisRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisRadioButtonActionPerformed(evt);
            }
        });

        tresRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(tresRadioButton);
        tresRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        tresRadioButton.setText("3");
        tresRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresRadioButtonActionPerformed(evt);
            }
        });

        quatroRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(quatroRadioButton);
        quatroRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        quatroRadioButton.setText("4");
        quatroRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroRadioButtonActionPerformed(evt);
            }
        });

        cincoRadioButton.setBackground(new java.awt.Color(255, 247, 247));
        buttonGroup1.add(cincoRadioButton);
        cincoRadioButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        cincoRadioButton.setText("5");
        cincoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoRadioButtonActionPerformed(evt);
            }
        });

        progressoSpinner.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        detalharButton.setBackground(new java.awt.Color(255, 204, 204));
        detalharButton.setFont(new java.awt.Font("Poor Richard", 0, 15)); // NOI18N
        detalharButton.setForeground(new java.awt.Color(153, 0, 0));
        detalharButton.setText("Detalhar");
        detalharButton.setFocusPainted(false);
        detalharButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detalharButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detalharButtonMouseExited(evt);
            }
        });
        detalharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalharButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel1.setText("Detalhes");

        jLabel5.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel5.setText("Nome: ");

        jLabel6.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel6.setText("Autor: ");

        jLabel7.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel7.setText("Gênero:");

        jLabel8.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel8.setText("Páginas:");

        jLabel9.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel9.setText("Páginas Lidas: ");

        jLabel10.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel10.setText("Sua nota:");

        nomejLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        nomejLabel.setForeground(new java.awt.Color(102, 102, 102));
        nomejLabel.setText("-");

        autorjLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        autorjLabel.setForeground(new java.awt.Color(102, 102, 102));
        autorjLabel.setText("-");

        generojLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        generojLabel.setForeground(new java.awt.Color(102, 102, 102));
        generojLabel.setText("-");

        paginasjLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        paginasjLabel.setForeground(new java.awt.Color(102, 102, 102));
        paginasjLabel.setText("-");

        paginasLidasjLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        paginasLidasjLabel.setForeground(new java.awt.Color(102, 102, 102));
        paginasLidasjLabel.setText("-");

        notajLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        notajLabel.setForeground(new java.awt.Color(102, 102, 102));
        notajLabel.setText("-");

        jLabel21.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        jLabel21.setText("Progresso:");

        progressojLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        progressojLabel.setForeground(new java.awt.Color(102, 102, 102));
        progressojLabel.setText("-");

        voltarButton1.setBackground(new java.awt.Color(255, 255, 255));
        voltarButton1.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton1.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconVoltar.png")); // NOI18N
        voltarButton1.setBorder(null);
        voltarButton1.setBorderPainted(false);
        voltarButton1.setContentAreaFilled(false);
        voltarButton1.setPressedIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconVoltarPres.png")); // NOI18N
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sairButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(progressoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(notaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(progressoSpinner)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3))
                            .addComponent(voltarButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(zeroRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(humRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doisRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tresRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quatroRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cincoRadioButton)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(paginasLidasjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(paginasjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(generojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(detalharButton)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(notajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(progressojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autorjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarButton1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zeroRadioButton)
                            .addComponent(humRadioButton)
                            .addComponent(doisRadioButton)
                            .addComponent(tresRadioButton)
                            .addComponent(quatroRadioButton)
                            .addComponent(cincoRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(progressoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelUsuario)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(detalharButton)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nomejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(autorjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(generojLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(paginasjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(paginasLidasjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(notajLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(progressojLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detalharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalharButtonActionPerformed
        int linha = estanteTable.getSelectedRow();

        try {
            if (linha >= 0) {
                nomejLabel.setText((String) estanteTable.getValueAt(linha, 1));
                autorjLabel.setText((String) estanteTable.getValueAt(linha, 2));
                generojLabel.setText((String) estanteTable.getValueAt(linha, 3));
                paginasjLabel.setText(Integer.toString((int) estanteTable.getValueAt(linha, 4)));
                paginasLidasjLabel.setText(Integer.toString((int) estanteTable.getValueAt(linha, 5)));
                notajLabel.setText(Integer.toString((int) estanteTable.getValueAt(linha, 6)));

                int lidas = (int) estanteTable.getValueAt(linha, 5);
                int total = (int) estanteTable.getValueAt(linha, 4);

                double calculo = (lidas * 100) / total;

                progressojLabel.setText(Double.toString(calculo) + "%");
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um livro");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel mostrar as informações do livro! " + ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_detalharButtonActionPerformed

    private void cincoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoRadioButtonActionPerformed

    private void quatroRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quatroRadioButtonActionPerformed

    private void tresRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresRadioButtonActionPerformed

    private void doisRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doisRadioButtonActionPerformed

    private void humRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humRadioButtonActionPerformed

    private void zeroRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroRadioButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        if (escolha == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Até a próxima!");
            this.dispose();
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        int linha = estanteTable.getSelectedRow();
        if (linha >= 0) {
            int id = (int) estanteTable.getValueAt(linha, 0);

            Livros livro = new Livros(id);
            try {
                DAOEstante.removerEstante(livro);
                ((DefaultTableModel) estanteTable.getModel()).removeRow(estanteTable.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Livro removido com sucesso!");
                nomejLabel.setText("-");
                autorjLabel.setText("-");
                generojLabel.setText("-");
                paginasjLabel.setText("-");
                paginasLidasjLabel.setText("-");
                notajLabel.setText("-");
                progressojLabel.setText("-");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao remover livro, tente novamente mais tarde... " + ex);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro");
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void progressoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressoButtonActionPerformed
        int linha = estanteTable.getSelectedRow();

        try {
            if (linha >= 0) {
                int id = (int) estanteTable.getValueAt(linha, 0);
                int paginasLidas = (int) progressoSpinner.getValue();

                int paginas = (int) estanteTable.getValueAt(linha, 4);

                Livros livros = new Livros(id, paginasLidas);

                if (paginasLidas >= 0) {
                    if (paginasLidas > paginas) {
                        JOptionPane.showMessageDialog(null, "Não tem como ler mais páginas do que o livro possui.");
                    } else {
                        DAOEstante.progressoLivro(livros, id);
                        progressoSpinner.setValue(0);
                        JOptionPane.showMessageDialog(null, "A leitura sempre agrega no nosso conhecimento.");
                        reiniciaTela();
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um livro");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Teste novamente mais tarde! " + ex);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_progressoButtonActionPerformed

    public void reiniciaTela() {
        String nome = jLabelUsuario.getText();
        TelaMinhaEstante viewEstante = new TelaMinhaEstante(nome);
        viewEstante.setVisible(true);
        this.dispose();
    }

    private void notaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaButtonActionPerformed

        String notaZero = zeroRadioButton.getText();
        String notaHum = humRadioButton.getText();
        String notaDois = doisRadioButton.getText();
        String notaTres = tresRadioButton.getText();
        String notaQuatro = quatroRadioButton.getText();
        String notaCinco = cincoRadioButton.getText();

        int linha = estanteTable.getSelectedRow();

        try {
            if (linha >= 0) {
                int id = (int) estanteTable.getValueAt(linha, 0);
                Livros notaLivros = new Livros(id);

                if (zeroRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaZero));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else if (humRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaHum));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else if (doisRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaDois));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else if (tresRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaTres));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else if (quatroRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaQuatro));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else if (cincoRadioButton.isSelected()) {
                    notaLivros.setNota(Integer.parseInt(notaCinco));
                    DAOEstante.avaliarLivro(notaLivros, id);
                    JOptionPane.showMessageDialog(null, "Nota atribuida, valeu!");
                    reiniciaTela();
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione a sua nota.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um livro.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde! " + ex);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_notaButtonActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        String nome = jLabelUsuario.getText();
        TelaMenu viewMenu = new TelaMenu(nome);
        viewMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void notaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notaButtonMouseEntered
        notaButton.setBackground(new Color(255, 168, 168));
        notaButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_notaButtonMouseEntered

    private void notaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notaButtonMouseExited
        notaButton.setBackground(new Color(255, 186, 186));
        notaButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_notaButtonMouseExited

    private void progressoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoButtonMouseEntered
        progressoButton.setBackground(new Color(255, 168, 168));
        progressoButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_progressoButtonMouseEntered

    private void progressoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressoButtonMouseExited
        progressoButton.setBackground(new Color(255, 186, 186));
        progressoButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_progressoButtonMouseExited

    private void removerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerButtonMouseEntered
        removerButton.setBackground(new Color(255, 168, 168));
        removerButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_removerButtonMouseEntered

    private void removerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerButtonMouseExited
        removerButton.setBackground(new Color(255, 186, 186));
        removerButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_removerButtonMouseExited

    private void sairButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseEntered
        sairButton.setBackground(new Color(255, 66, 66));
        sairButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_sairButtonMouseEntered

    private void sairButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseExited
        sairButton.setBackground(new Color(255, 91, 91));
        sairButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_sairButtonMouseExited

    private void detalharButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalharButtonMouseEntered
        detalharButton.setBackground(new Color(255, 168, 168));
        detalharButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_detalharButtonMouseEntered

    private void detalharButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalharButtonMouseExited
        detalharButton.setBackground(new Color(255, 186, 186));
        detalharButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_detalharButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMinhaEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMinhaEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMinhaEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMinhaEstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMinhaEstante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorjLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cincoRadioButton;
    private javax.swing.JButton detalharButton;
    private javax.swing.JRadioButton doisRadioButton;
    private javax.swing.JTable estanteTable;
    private javax.swing.JLabel generojLabel;
    private javax.swing.JRadioButton humRadioButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JButton notaButton;
    private javax.swing.JLabel notajLabel;
    private javax.swing.JLabel paginasLidasjLabel;
    private javax.swing.JLabel paginasjLabel;
    private javax.swing.JButton progressoButton;
    private javax.swing.JSpinner progressoSpinner;
    private javax.swing.JLabel progressojLabel;
    private javax.swing.JRadioButton quatroRadioButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JRadioButton tresRadioButton;
    private javax.swing.JButton voltarButton1;
    private javax.swing.JRadioButton zeroRadioButton;
    // End of variables declaration//GEN-END:variables
}
