/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Livros;
import classes.Usuarios;
import dao.DAOEstante;
import dao.DAOLivros;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telas.funcoesBiblioteca.TelaAdicionar;
import telas.funcoesBiblioteca.TelaEditarLivros;

/**
 *
 * @author natim
 */
public class TelaBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form TelaBiblioteca
     */
    public TelaBiblioteca(String usuario) {
        super("Biblioteca");
        initComponents();
        jLabelUsuario.setText(usuario);

        setLocationRelativeTo(null);

        DefaultTableModel modelo = (DefaultTableModel) bibliotecaTable.getModel();

        bibliotecaTable.getColumnModel().getColumn(0);
        bibliotecaTable.getColumnModel().getColumn(1);
        bibliotecaTable.getColumnModel().getColumn(2);
        bibliotecaTable.getColumnModel().getColumn(3);
        bibliotecaTable.getColumnModel().getColumn(4);
        DAOLivros daoL = new DAOLivros();
        try {
            for (Livros m : daoL.listarLivros()) {
                modelo.addRow(new Object[]{
                    m.getId_Livros(),
                    m.getNome(),
                    m.getAutor(),
                    m.getGenero(),
                    m.getPaginas()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar as músicas!");
        }
    }

    public TelaBiblioteca() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        addEstanteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bibliotecaTable = new javax.swing.JTable();
        adicionarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        recarregarButton = new javax.swing.JButton();
        voltarButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 247, 247));

        addEstanteButton.setBackground(new java.awt.Color(255, 204, 204));
        addEstanteButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addEstanteButton.setForeground(new java.awt.Color(153, 0, 0));
        addEstanteButton.setText("+");
        addEstanteButton.setFocusPainted(false);
        addEstanteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEstanteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEstanteButtonMouseExited(evt);
            }
        });
        addEstanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEstanteButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\BookShelf.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabel1.setText("Usuario: ");

        jLabelUsuario.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("jLabelUsuario");

        bibliotecaTable.setBackground(new java.awt.Color(255, 255, 255));
        bibliotecaTable.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        bibliotecaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor", "Gênero", "Páginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bibliotecaTable.setSelectionBackground(new java.awt.Color(255, 204, 204));
        bibliotecaTable.setSelectionForeground(new java.awt.Color(255, 51, 51));
        bibliotecaTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                bibliotecaTableComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(bibliotecaTable);
        if (bibliotecaTable.getColumnModel().getColumnCount() > 0) {
            bibliotecaTable.getColumnModel().getColumn(0).setResizable(false);
            bibliotecaTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            bibliotecaTable.getColumnModel().getColumn(1).setResizable(false);
            bibliotecaTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            bibliotecaTable.getColumnModel().getColumn(2).setResizable(false);
            bibliotecaTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            bibliotecaTable.getColumnModel().getColumn(3).setResizable(false);
            bibliotecaTable.getColumnModel().getColumn(4).setResizable(false);
        }

        adicionarButton.setBackground(new java.awt.Color(255, 204, 204));
        adicionarButton.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        adicionarButton.setForeground(new java.awt.Color(153, 0, 0));
        adicionarButton.setText("Adicionar");
        adicionarButton.setFocusPainted(false);
        adicionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adicionarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adicionarButtonMouseExited(evt);
            }
        });
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        removerButton.setBackground(new java.awt.Color(255, 91, 91));
        removerButton.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        removerButton.setForeground(new java.awt.Color(153, 0, 0));
        removerButton.setText("Remover");
        removerButton.setFocusPainted(false);
        removerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removerButtonMouseExited(evt);
            }
        });
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        editarButton.setBackground(new java.awt.Color(255, 204, 204));
        editarButton.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        editarButton.setForeground(new java.awt.Color(153, 0, 0));
        editarButton.setText("Editar");
        editarButton.setFocusPainted(false);
        editarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarButtonMouseExited(evt);
            }
        });
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        sairButton.setBackground(new java.awt.Color(255, 91, 91));
        sairButton.setFont(new java.awt.Font("Poor Richard", 0, 16)); // NOI18N
        sairButton.setForeground(new java.awt.Color(153, 0, 0));
        sairButton.setText("Sair");
        sairButton.setFocusPainted(false);
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairButtonMouseExited(evt);
            }
        });
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Gostou? Adicione na sua estante");

        recarregarButton.setBackground(new java.awt.Color(255, 255, 255));
        recarregarButton.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconRefresh.png")); // NOI18N
        recarregarButton.setBorder(null);
        recarregarButton.setBorderPainted(false);
        recarregarButton.setContentAreaFilled(false);
        recarregarButton.setPressedIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconRefreshPres.png")); // NOI18N
        recarregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recarregarButtonActionPerformed(evt);
            }
        });

        voltarButton1.setBackground(new java.awt.Color(255, 255, 255));
        voltarButton1.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton1.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconVoltar.png")); // NOI18N
        voltarButton1.setBorder(null);
        voltarButton1.setBorderPainted(false);
        voltarButton1.setContentAreaFilled(false);
        voltarButton1.setPressedIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\iconVoltarPres.png")); // NOI18N
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poor Richard", 0, 12)); // NOI18N
        jLabel4.setText("Atualize as músicas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltarButton1)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(removerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adicionarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addEstanteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recarregarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recarregarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(voltarButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEstanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsuario))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        if (escolha == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Até a próxima!");
            this.dispose();
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
        TelaAdicionar viewAdc = new TelaAdicionar();
        viewAdc.setVisible(true);
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        int linha = bibliotecaTable.getSelectedRow();
        if (linha >= 0) {
            int id = (int) bibliotecaTable.getValueAt(linha, 0);

            Livros livro = new Livros(id);
            try {
                DAOLivros.removerBiblioteca(livro);
                ((DefaultTableModel) bibliotecaTable.getModel()).removeRow(bibliotecaTable.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Livro removido com sucesso!");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao remover livro, tente novamente mais tarde... " + ex);
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro");
        }


    }//GEN-LAST:event_removerButtonActionPerformed

    private void recarregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recarregarButtonActionPerformed
        String nome = jLabelUsuario.getText();
        TelaBiblioteca telaBiblioteca = new TelaBiblioteca(nome);
        telaBiblioteca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recarregarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed

        int linha = bibliotecaTable.getSelectedRow();
        if (linha >= 0) {
            int id = (int) bibliotecaTable.getValueAt(linha, 0);
            String nome = (String) bibliotecaTable.getValueAt(linha, 1);
            String autor = (String) bibliotecaTable.getValueAt(linha, 2);
            String genero = (String) bibliotecaTable.getValueAt(linha, 3);
            int paginas = (int) bibliotecaTable.getValueAt(linha, 4);

            TelaEditarLivros viewEdit = new TelaEditarLivros(id, nome, autor, genero, paginas);
            viewEdit.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro");
        }


    }//GEN-LAST:event_editarButtonActionPerformed

    private void addEstanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEstanteButtonActionPerformed
        int linha = bibliotecaTable.getSelectedRow();
        if (linha >= 0) {

            String nome = (String) bibliotecaTable.getValueAt(linha, 1);
            String autor = (String) bibliotecaTable.getValueAt(linha, 2);
            String genero = (String) bibliotecaTable.getValueAt(linha, 3);
            int paginas = (int) bibliotecaTable.getValueAt(linha, 4);

            String usuarioLogado = (String) jLabelUsuario.getText();

            Livros livros = new Livros(nome, autor, genero, paginas);
            Usuarios usuario = new Usuarios(usuarioLogado);

            try {
                DAOEstante.adicionarEstante(livros, usuario);
                JOptionPane.showMessageDialog(null, "Livro adicionado em sua estante!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não foi possivel adicionar esse livro a sua estante." + ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um livro");
        }
    }//GEN-LAST:event_addEstanteButtonActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        String nome = jLabelUsuario.getText();
        TelaMenu viewMenu = new TelaMenu(nome);
        viewMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void adicionarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarButtonMouseEntered
        adicionarButton.setBackground(new Color(255, 168, 168));
        adicionarButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_adicionarButtonMouseEntered

    private void adicionarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarButtonMouseExited
        adicionarButton.setBackground(new Color(255, 186, 186));
        adicionarButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_adicionarButtonMouseExited

    private void editarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarButtonMouseEntered
        editarButton.setBackground(new Color(255, 168, 168));
        editarButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_editarButtonMouseEntered

    private void editarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarButtonMouseExited
        editarButton.setBackground(new Color(255, 186, 186));
        editarButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_editarButtonMouseExited

    private void removerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerButtonMouseEntered
        removerButton.setBackground(new Color(255,66,66));
        removerButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_removerButtonMouseEntered

    private void removerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerButtonMouseExited
        removerButton.setBackground(new Color(255,91,91));
        removerButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_removerButtonMouseExited

    private void sairButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseEntered
        sairButton.setBackground(new Color(255,66,66));
        sairButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_sairButtonMouseEntered

    private void sairButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseExited
        sairButton.setBackground(new Color(255,91,91));
        sairButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_sairButtonMouseExited

    private void addEstanteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEstanteButtonMouseEntered
        addEstanteButton.setBackground(new Color(255, 168, 168));
        addEstanteButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_addEstanteButtonMouseEntered

    private void addEstanteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEstanteButtonMouseExited
        addEstanteButton.setBackground(new Color(255, 186, 186));
        addEstanteButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_addEstanteButtonMouseExited

    private void bibliotecaTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_bibliotecaTableComponentAdded
        bibliotecaTable.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bibliotecaTableComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEstanteButton;
    private javax.swing.JButton adicionarButton;
    private javax.swing.JTable bibliotecaTable;
    private java.awt.Button button1;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recarregarButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
