/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author natim
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu(String usuario) {
        super("Menu");
        initComponents();
        jLabelUsuario.setText(usuario);
        setLocationRelativeTo(null);
    }

    public TelaMenu() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        estanteButton = new javax.swing.JButton();
        bibliotecaLivros = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        recomendaLivros = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\BookShelf.png")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(78, 78, 78))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 247, 247));

        jLabelUsuario.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuario.setText("-");

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabel1.setText("Usuario: ");

        jPanel3.setBackground(new java.awt.Color(246, 232, 232));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\natim\\Desktop\\Estudos\\Desenvolvimento\\BookShelf\\BookShelf\\src\\main\\java\\images\\BookShelf.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, Short.MAX_VALUE))
        );

        estanteButton.setBackground(new java.awt.Color(255, 204, 204));
        estanteButton.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        estanteButton.setForeground(new java.awt.Color(153, 0, 0));
        estanteButton.setText("Minha Estante");
        estanteButton.setFocusPainted(false);
        estanteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estanteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estanteButtonMouseExited(evt);
            }
        });
        estanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estanteButtonActionPerformed(evt);
            }
        });

        bibliotecaLivros.setBackground(new java.awt.Color(255, 204, 204));
        bibliotecaLivros.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        bibliotecaLivros.setForeground(new java.awt.Color(153, 0, 0));
        bibliotecaLivros.setText("Biblioteca");
        bibliotecaLivros.setFocusPainted(false);
        bibliotecaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bibliotecaLivrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bibliotecaLivrosMouseExited(evt);
            }
        });
        bibliotecaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaLivrosActionPerformed(evt);
            }
        });

        sairButton.setBackground(new java.awt.Color(255, 91, 91));
        sairButton.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        sairButton.setForeground(new java.awt.Color(153, 0, 0));
        sairButton.setText("Sair");
        sairButton.setFocusPainted(false);
        sairButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairButtonMouseExited(evt);
            }
        });
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        recomendaLivros.setBackground(new java.awt.Color(255, 204, 204));
        recomendaLivros.setFont(new java.awt.Font("Poor Richard", 0, 19)); // NOI18N
        recomendaLivros.setForeground(new java.awt.Color(153, 0, 0));
        recomendaLivros.setText("Recomendações");
        recomendaLivros.setFocusPainted(false);
        recomendaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recomendaLivrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recomendaLivrosMouseExited(evt);
            }
        });
        recomendaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recomendaLivrosActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton.setText("Clique aqui");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Deseja trocar de usuário?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estanteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bibliotecaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recomendaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(estanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bibliotecaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recomendaLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoutButton)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabelUsuario)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        if (escolha == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Até a próxima!");
            this.dispose();
        }
    }//GEN-LAST:event_sairButtonActionPerformed

    private void estanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estanteButtonActionPerformed
        String nome = jLabelUsuario.getText();
        TelaMinhaEstante viewEstante = new TelaMinhaEstante(nome);
        viewEstante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_estanteButtonActionPerformed

    private void bibliotecaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaLivrosActionPerformed
        String nome = jLabelUsuario.getText();
        TelaBiblioteca viewEstante = new TelaBiblioteca(nome);
        viewEstante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bibliotecaLivrosActionPerformed

    private void recomendaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomendaLivrosActionPerformed
        String nome = jLabelUsuario.getText();
        TelaRecomendacoes viewRecomenda = new TelaRecomendacoes(nome);
        viewRecomenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recomendaLivrosActionPerformed

    private void estanteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estanteButtonMouseEntered
        estanteButton.setBackground(new Color(255, 168, 168));
        estanteButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_estanteButtonMouseEntered

    private void estanteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estanteButtonMouseExited
        estanteButton.setBackground(new Color(255, 186, 186));
        estanteButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_estanteButtonMouseExited

    private void bibliotecaLivrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaLivrosMouseEntered
        bibliotecaLivros.setBackground(new Color(255, 168, 168));
        bibliotecaLivros.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bibliotecaLivrosMouseEntered

    private void bibliotecaLivrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibliotecaLivrosMouseExited
        bibliotecaLivros.setBackground(new Color(255, 186, 186));
        bibliotecaLivros.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_bibliotecaLivrosMouseExited

    private void recomendaLivrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendaLivrosMouseEntered
        recomendaLivros.setBackground(new Color(255, 168, 168));
        recomendaLivros.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_recomendaLivrosMouseEntered

    private void recomendaLivrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendaLivrosMouseExited
        recomendaLivros.setBackground(new Color(255, 186, 186));
        recomendaLivros.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_recomendaLivrosMouseExited

    private void sairButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseEntered
        sairButton.setBackground(new Color(255,66,66));
        sairButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_sairButtonMouseEntered

    private void sairButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairButtonMouseExited
        sairButton.setBackground(new Color(255,91,91));
        sairButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_sairButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        TelaLogin viewLogin = new TelaLogin();
        JOptionPane.showMessageDialog(null, "Até mais!");
        viewLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
       logoutButton.setForeground(new Color(153, 0, 0));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_logoutButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bibliotecaLivros;
    private javax.swing.JButton estanteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton recomendaLivros;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
